dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
cache: pip
install:
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: osma
  password:
    secure: CaIkcMjLfOokfnWvNwGHAJ/suOyjI+DY8EMnzGi/fyCNff566PhjGuqb0q4/xGI/PgY0JqSspa5GAM222wqH0JLJAmVcsb/5cMexhovIHnnvbR1ViHVCyFdQkPWnnWxvqFgSoEoJhyQqP3oHxl1lhSdSSgJvEtQBik8xTYoWpyC/nBGsjyuHU5mNZjTdT1X1UlLvzOswBQJ0LZDdzGGZRw1zvl0r6XWAgOSEu+XsAR1PvrXcgmwYtC+0YoMbZccwFTu7ubfYjPjC5P61Y0RloG7PKHo0mkT9XMicUKiOFkPkS/V6k45rmle70Yib0S06SJe7Z6GUCGZTZpgTlx7gVVD3Omn9+KCJEAt5/0F6fekaKjmUnpXaLwFCaD+t1aip0EmDi3YDgV5PQ8XEMFdE2YZ2bue3n5TX/TXTLAZThTyhvofiYYsvRw+FrQ5imbW9ExJxW4R9SOhr6oGd7yJqgDApP4JAZg53UQ+xElKOWVXJmuskrONwpfx4r+EPV2wPIgA9Zcrd+o61S5Au/bKNZPuXCBAnq//o8PtWCkOIJfrexvCechTjXTbhu2APsB0xdFkJSIVvuwqF0pKUb9xpyRAX+vers6MgpEu2sE8NP9f9RetK7h4VxOGMkNNNVbDWNJ41t/88QR4tB7673l3HLYSo7pMbep2l5G+IJtSzzcY=
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true
